# Generated by Django 2.2 on 2020-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_images', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
